services:

  telegraf-1: &telegraf 
    image: telegraf:1.33.3
    container_name: telegraf-1
    hostname: telegraf-1
    volumes: 
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - redpanda

  telegraf-2: 
    <<: *telegraf
    container_name: telegraf-2
    hostname: telegraf-2

  telegraf-3: 
    <<: *telegraf
    container_name: telegraf-3
    hostname: telegraf-3

  redpanda:
    container_name: redpanda
    hostname: redpanda
    image: redpandadata/redpanda:v24.3.6
    command:
      -   redpanda start --smp 1 --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --rpc-addr redpanda:33145 --advertise-rpc-addr redpanda:33145
      - --mode dev-container
    volumes:
      - ./config/redpanda/bootstrap.yaml:/etc/redpanda/.bootstrap.yaml
    ports:
      - 19092:19092

  clickhouse:
    container_name: clickhouse
    hostname: clickhouse
    image: clickhouse:25.1.5.31
    volumes:
      - ./config/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./config/clickhouse:/scripts
    ports:
      - 9000:9000

  metric-router-1:
    image: metric-router:1.1
    container_name: metric-router-1
    hostname: metric-router-1
    volumes:
      - ./code/metric-router/:/app
    depends_on:
      - redpanda
    ports:
      - 8001:8000

  metric-router-2:
    image: metric-router:1.1
    container_name: metric-router-2
    hostname: metric-router-2
    volumes:
      - ./code/metric-router/:/app
    depends_on:
      - redpanda
    ports:
      - 8002:8000

  prometheus:
    image: prom/prometheus:v3.2.1
    container_name: prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - ./config/grafana/dashboards:/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

networks:
  default:
    name: metric-pipe
