[consumer]
bootstrap_servers = "redpanda:9092"
group_id = "metrics"
kafka_topic = "telegraf"

[writer]
db_server = "clickhouse"
db_server_port = 9000
max_bucket_size = 100
bucket_time_trigger = 60
max_bucket_age = 300
writer_sleep = 3