{
 "title": "Metric Router",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Data Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingress Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(metric_rtr_kafka_read_bytes_total[10s])",
     "legendFormat": "Data Rate"
    }
   ]
  },
  {
   "title": "Ingress Message Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(metric_rtr_kafka_reads_total[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internal Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Metric Bucket Sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "metric_rtr_bucket_size{}", "legendFormat": "Bucket Size: {{metric_name}}" }
   ]
  },
  {
   "title": "Msg Unpacked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(metric_rtr_msg_decoded_total[10s])",
     "legendFormat": "Msg Unpacked"
    }
   ]
  },
  {
   "title": "Measurement Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metric_rtr_measurement_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Measurement Pruned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metric_rtr_measurements_pruned_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Measurement Flush on Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metric_rtr_flush_on_time_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Measurement Flush on Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "metric_rtr_flush_on_size_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Database Inserts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(metric_rtr_db_inserts_total[10s])",
     "legendFormat": "DB Inserts"
    }
   ]
  },
  {
   "title": "Database Insert Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(metric_rtr_db_insert_fail_total[1m])",
     "legendFormat": "DB Inserts"
    }
   ]
  },
  {
   "title": "DB Insert Row Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "metric_rtr_insert_size", "legendFormat": "{{label_name}}" }
   ]
  }
 ]
}