global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'metric-router'
    static_configs:
      - targets:
          - metric-router-1:8000
          - metric-router-2:8000

  - job_name: redpanda-public
    static_configs:
      - targets:
        - redpanda:9644
    metrics_path: /public_metrics

  # - job_name: redpanda-internal
  #   static_configs:
  #   - targets:
  #       - redpanda:9644
  #   metrics_path: /metrics
